"""
Django settings for glyph project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import logging
import os
import platform
import sys

from . import load_utils as load

if platform.python_version_tuple() < ('3', '7'):
    raise RuntimeError(
        'Glyph requires Python 3.7 or higher (current: Python {})'.format(
            platform.python_version()
        )
    )


def is_testing(argv=None):
    """Return True if running django or py.test unit tests.
    """
    if 'PYTEST_CURRENT_TEST' in os.environ.keys():
        return True
    argv = sys.argv if argv is None else argv
    if len(argv) >= 1 and ('py.test' in argv[0] or 'py/test.py' in argv[0]):
        return True
    return len(argv) >= 2 and argv[1] in ['test', 'lint']


def is_management_cmd(argv=None):
    if not argv:
        argv = sys.argv
    return len(argv) > 1 and argv[1] in ['collectstatic', 'check_db']


def insecure_secret_key_allowed(argv=None):
    return is_testing(argv) or is_management_cmd(argv)


IS_TESTING = is_testing()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Project root that contains this entire project, not just the python code
PROJECT_DIR = os.path.dirname(BASE_DIR)

# App directory where apps are located
APP_DIR = os.path.join(BASE_DIR, 'apps')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = load.getenv('DEBUG', bool, default=True)

# SECURITY WARNING: keep the secret key used in production secret!
_default_secret_key = 'iamabadsecretkey'
SECRET_KEY = load.getenv('SECRET_KEY', str, default='iamabadsecretkey')
if not insecure_secret_key_allowed() and SECRET_KEY == _default_secret_key and not DEBUG:
    raise AssertionError('Please provide a better SECRET_KEY that is not the default.')

ALLOWED_HOSTS = load.getenv('ALLOWED_HOSTS', list, default=['*'])
if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError('ALLOWED_HOSTS cannot be empty when not in DEBUG')

if not DEBUG:
    SECURE_HSTS_SECONDS = load.getenv('SECURE_HSTS_SECONDS', int, default=60)
    CSRF_COOKIE_SECURE = load.getenv('CSRF_COOKIE_SECURE', bool, default=True)
    SECURE_HSTS_PRELOAD = load.getenv('SECURE_HSTS_PRELOAD', bool, default=True)
    SECURE_SSL_REDIRECT = load.getenv('SECURE_SSL_REDIRECT', bool, default=True)
    X_FRAME_OPTIONS = load.getenv('X_FRAME_OPTIONS', str, default='DENY').upper()
    SESSION_COOKIE_SECURE = load.getenv('SESSION_COOKIE_SECURE', bool, default=True)
    SECURE_BROWSER_XSS_FILTER = load.getenv('SECURE_BROWSER_XSS_FILTER', bool, default=True)
    SECURE_CONTENT_TYPE_NOSNIFF = load.getenv('SECURE_CONTENT_TYPE_NOSNIFF', bool, default=True)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = load.getenv(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS',
        bool,
        default=True
    )

# Cors Configuration
# https://github.com/adamchainz/django-cors-headers

CORS_ORIGIN_ALLOW_ALL = DEBUG
CORS_ORIGIN_WHITELIST = load.getenv(
    'CORS_ORIGIN_WHITELIST',
    list,
    default=[
        'http://localhost:8080', 'http://127.0.0.1:8080',
        'http://localhost:3000', 'http://127.0.0.1:3000',
    ]
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'glyph.commands',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'glyph.configuration.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'glyph.configuration.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DEFAULT_DATABASE_TYPE = 'sqlite'
DATABASE_TYPE = load.getenv('DATABASE_TYPE', str, default=DEFAULT_DATABASE_TYPE).lower()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

if DATABASE_TYPE == 'memory':
    DATABASES['default']['NAME'] = ':memory:'
elif DATABASE_TYPE != DEFAULT_DATABASE_TYPE:
    DATABASES = {
        'default': {
            'ENGINE': f'django.db.backends.{DATABASE_TYPE}',
            'NAME': load.getenv('DATABASE_DB', str),
            'USER': load.getenv('DATABASE_USER', str),
            'PASSWORD': load.getenv('DATABASE_PASSWORD', str),
            'HOST': load.getenv('DATABASE_HOST', str),
            'PORT': load.getenv('DATABASE_PORT', str, default='5432'),
        }
    }

# Use the DATABASE_URL if provided in the environment by Heroku
if load.getenv('DATABASE_URL', str, default='') != '':
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(conn_max_age=600)


# Caching

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'
    }
}

USE_MEMCACHIER = load.getenv('USE_MEMCACHIER', bool, default=False)
if USE_MEMCACHIER:
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.memcached.PyLibMCCache',
        # TIMEOUT is not the connection timeout! It's the default expiration
        # timeout that should be applied to keys! Setting it to `None`
        # disables expiration.
        'TIMEOUT': None,
        'LOCATION': load.getenv('MEMCACHIER_SERVERS', str),
        'OPTIONS': {
            'binary': True,
            'username': load.getenv('MEMCACHIER_USERNAME', str),
            'password': load.getenv('MEMCACHIER_PASSWORD', str),
            'behaviors': {
                # Enable faster IO
                'no_block': True,
                'tcp_nodelay': True,
                # Keep connection alive
                'tcp_keepalive': True,
                # Timeout settings
                'connect_timeout': 2000,  # ms
                'send_timeout': 750 * 1000,  # us
                'receive_timeout': 750 * 1000,  # us
                '_poll_timeout': 2000,  # ms
                # Better failover
                'ketama': True,
                'remove_failed': 1,
                'retry_timeout': 2,
                'dead_timeout': 30,
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected-static')

# Logging
# https://docs.djangoproject.com/en/3.1/topics/logging/

LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
            'formatter': 'simple' if DEBUG else 'verbose'
        },
        'glyph': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
            'formatter': 'simple' if DEBUG else 'verbose'
        },
        'celery': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
    },
}

if IS_TESTING:
    logging.disable(logging.CRITICAL)
